version: '2'
services:
  nodejs:
    build: ./nodejs
    container_name: nodejs
    expose:
        - "8080"
    ports:
        - "8080:8080"
    networks:
        - frontend
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
        - nodejs
    links:
        - nodejs
    ports:
        - "80:80"
    networks:
        - frontend
networks:
    frontend: